v4: adjusments to core utility types
contentful/forma-36 pull request #1228
Opened 2021-08-25 10:55 UTC by bgutsol

# Purpose of PR
It's unclear now when/how to use types for polymorphic components or for components that are not polymorphic but need to extend their own props with the default HTML element one.
That's why we ended up having slightly different approaches in our codebase:
- To extend own props we use [PolymorphicComponentProps with unchangeable as prop](https://github.com/contentful/forma-36/blob/c9991a83905b9ebac727946a69a941065ae20afb/packages/components/note/src/Note.tsx#L52)., It seems confusing, because we give `as` prop but fixing it to only one value.
- With the [DragHandle component](https://github.com/contentful/forma-36/blob/673e7b39d637afe6d7afa8d1147aa2e24b838525/packages/components/drag-handle/src/DragHandle.tsx#L116) and [List](https://github.com/contentful/forma-36/blob/7e4dc05b740bfc47dbc52c40224dec424d6af841/packages/components/list/src/List.tsx#L31) components I didn't get the idea at all.
- We also for some reason include `CommonProps` initially [to Polymorphic component types](https://github.com/contentful/forma-36/blob/bf0fc7d5b9aa74009825588d822befe018c055ad/packages/core/src/Primitive/Primitive.tsx#L5) and then extending it in component one more time (ex. [Note](https://github.com/contentful/forma-36/blob/c9991a83905b9ebac727946a69a941065ae20afb/packages/components/note/src/Note.tsx#L29), [Button](https://github.com/contentful/forma-36/blob/ca7a3f7775bc2ee64ec80eb1fe09ddf7a9e91836/packages/components/button/src/types.ts#L20))
- The other question is why in some cases we use [usePrimitive](https://github.com/contentful/forma-36/blob/bf0fc7d5b9aa74009825588d822befe018c055ad/packages/core/src/Primitive/Primitive.tsx#L41) helper and in some we are not. What the purpose of this function. And do we need to use it everywhere where we have polymorphic component?

### The PR itself is just a proposal how everything described above can be done in a slightly different way. Just to simplify and bring a bit more clarity
New types working fine with storybook knobs generation and our website docs `<Props of="Component" />`

## PR Checklist

- [ ] I have read the relevant `readme.md` file(s)
- [ ] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [ ] Tests are added/updated/not required
- [ ] Tests are passing
- [ ] Storybook stories are added/updated/not required
- [ ] Usage notes are added/updated/not required
- [ ] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [ ] Doesn't contain any sensitive information

2021-08-25 12:10 UTC, suevalov reviewed
I think it's the way better - more concise and easier to understand

2021-08-25 14:25 UTC, denkristoffer commented
There's definitely some confusion here 😁

I think some of it is due to us changing our minds and refactoring things after the initial implementations of these ideas, which led to different understandings of how to implement these things. Speaking only for myself, `Primitive`, for example, was initially a component that I imagined as a base for all other components. It was changed to a hook for performance reasons, and I think I kept using it while others maybe didn't. Perhaps the polymorphic types have the same issue. I always imagined it as a global thing we would use everywhere to let consumers render components with the tags of their choice.  

It comes down to not having fully aligned on the strategy, I think. Overall we need a final cleanup and alignment before release 🙂

2021-08-25 14:28 UTC, gui-santos requested changes
I liked it!

Hey, do you think using [type-fest](https://github.com/sindresorhus/type-fest) would help us?

2021-08-25 14:28 UTC, gui-santos commented on packages/components/text-link/TextLink.mdx
> +## Props of DateTime
```suggestion
## Props of TextLink
```

2021-08-25 14:28 UTC, gui-santos commented on packages/components/datetime/src/DateTime.tsx
> +interface DateTimeOwnProps extends CommonProps {
Yep, let's rename everything to `OwnProps` in another PR if we decide to do that

2021-08-30 10:23 UTC, bgutsol reviewed
So to sum up:
1. I will refactor old polymorphic types with the new one.
2. Instead of using polymorphic in the place where we just need to extend the props with the default html element attrs, I will use new type `PropsWithHTMLElement`
3. I will not rename `InternalProps` to `OwnProps` since we are using `InternalProps` everywhere and I don't see the value in such changes.
4. I will delete `usePrimitive` function and its usage.

2021-08-30 10:34 UTC, suevalov commented
> I will delete `usePrimitive` function and its usage.

I'd still leave it and use for `Box`, `Flex` and `Grid` components without exporting it out of the package.

2021-08-31 12:55 UTC, suevalov commented on packages/components/list/src/List.tsx
> +export const List = React.forwardRef<HTMLUListElement, ListProps>(
IMO, `List` should still be polymorphic.

2021-08-31 12:58 UTC, suevalov reviewed
Just one comment about List

2021-08-31 19:08 UTC, suevalov approved these changes
🎖️ for 👨🏼‍💻

2021-09-01 06:50 UTC, burakukula approved these changes
Looks great! 🎉
Maybe we could come up later on with some form of guidelines for contributors if anyone would create a new component, how to use those. But we can tackle it later.

2021-09-01 07:51 UTC, merged