chore(inline-entry-card): add codemod for inline entry card
contentful/forma-36 pull request #1531
Opened 2021-11-16 16:13 UTC by thebesson

# Purpose of PR

## PR Checklist

- [ ] I have read the relevant `readme.md` file(s)
- [ ] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [ ] Tests are added/updated/not required
- [ ] Tests are passing
- [ ] Storybook stories are added/updated/not required
- [ ] Usage notes are added/updated/not required
- [ ] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [ ] Doesn't contain any sensitive information

2021-11-16 16:23 UTC, gui-santos approved these changes

2021-11-16 16:38 UTC, massao requested changes
Need to add the choice to inquirer, and update the tests file.
You can also use the `yarn generate codemod` to create the codemod files and it would also update the files as necessary.

2021-11-17 11:35 UTC, massao commented on packages/forma-36-codemod/README.md
> +#### `v4-v4-inline-entry-card`
the v4 is duplicated, on some other files too, just need to clean this up

2021-11-18 09:30 UTC, massao commented on packages/forma-36-codemod/transforms/__tests__/v4.test.js
> +    'v4-v4-inline-entry-card',
This is the only one missing:
```suggestion
    'v4-inline-entry-card',
```

2021-11-18 14:38 UTC, massao approved these changes

2021-11-18 15:08 UTC, merged