docs: add DragHandle documentation page
contentful/forma-36 pull request #1583
Opened 2021-12-03 10:57 UTC by massao

2021-12-03 14:02 UTC, gui-santos requested changes
Looks great!

I only have one important suggestion to implement the Props section title with a link to storybook

2021-12-03 14:02 UTC, gui-santos commented on packages/components/drag-handle/DragHandle.mdx
> +## Props (API reference)
Could you rebase this branch before merging it?

I made a change to this title in the plop template that is already merged. It's a couple of react components now and it includes a link to storybook page

Check the documentation of Accordion to see what to do, but this is how I think the code needs to be here

```suggestion
<Stack justifyContent="space-between" marginTop="spacing2Xl" marginBottom="spacingL">
  <Heading id="props-api-reference" as="h2" marginTop="none" marginBottom="none">
    Props (API reference)
  </Heading>

  <TextLink
    href="https://v4-f36-storybook.netlify.app/?path=/story/components-draghandle"
    target="_blank"
    alignIcon="end"
    icon={<ExternalLinkIcon />}
  >
    Open in Storybook
  </TextLink>
</Stack>
```

But you will need to import these components in the MDX file or this page will break

2021-12-03 14:23 UTC, massao commented on packages/components/drag-handle/DragHandle.mdx
> +```
Good catch, seems like the `Card` component has no styling for the drag handle, only the `AssetCard`, and the `EntryCard`, but `Card` still accepts the `withDragHandle` 🤔 
I'll just remove the withDragHandle from the Card for now, and keep on the other twos, so this PR is not blocked by this, and we can check later why it's like this

2021-12-06 12:36 UTC, gui-santos approved these changes

2021-12-06 12:39 UTC, bgutsol approved these changes

2021-12-06 15:41 UTC, merged