feat: add "full-with-seconds" datetime format
contentful/forma-36 pull request #1720
Opened 2022-01-07 14:07 UTC by andipaetzold

- ci: allow publising next-v4 changes
- chore: adjust publish command
- v4 feat: remove InViewport (#814)
- v4 feat(postcss): use @contentful/browserslist-config (#812)
- chore: configure data-test-id selector (#829)
- v4 feat: align prop interface names (#839)
- feat(portal): export for external consumption (#836)
- v4: remove alpha components (#851)
- feat v4: rename packages (#853)
- feat: extract Badge to a separate package (#857)
- fix: lint error
- fix: typo
- feat: extract Portal and TabFocusTrap to f36-utils package (#862)
- fix: modal background
- v4 chore: upgrade to TypeScript v4 (#865)
- chore(deps): upgrade browserslist-config
- v4 feat: stable Timepicker and Datepicker (#873)
- feat: primitive component (#830)
- feat: move grid to core
- feat: move Grid and GridItem to a separate layout component
- feat: move Flex to f36-layout
- chore: update all imports and remove all typescript errors
- chore: update snapshots
- chore: update snapshots
- chore: remove link to readme
- chore: move Flex and Grid to f36-core
- fix: correct imports and exports
- fix: imports
- feat: Box component (#878)
- fix: documentation website for forma-v4 (#882)
- chore: fix merge
- chore: merge fixes
- feat: shared types (#864)
- docs: Box & Flex on the documentation website (#887)
- docs: props table generation (#888)
- feat: typography package (#889)
- feat: add featured variant to Badge (#892)
- refactor: revert to plain emotion (#890)
- chore: generate token types (#893)
- feat: icons packages (#879)
- build: fix build after merge
- Rename README.md.hbs to README.mdx.hbs
- Update package.json.hbs
- Update README.mdx.hbs
- v4 feat(validation-message): refactor to v4 component (#914)
- fix(validation-message): use FlexInternalProps (#919)
- feat: extract List to a separate package (#918)
- Update README.mdx
- feat(spinner): refactor to v4 component (#916)
- feat: create new component package for controlled input
- feat: add story and working forwardRed, adapt styles
- feat: drop old ControlledInput and adapt usages and snapshots
- fix: styles, PR feedback, merge ref types
- fix: forwardRef points to root elements
- feat: pass new boxProps to wrapper div
- feat: pass otherProps through to box instead of input
- fix: move test id for controlled input to root element
- Update packages/components/controlled-input/src/ControlledInput.tsx
- style: shorten emotion selectors, remove undefined ref
- refactor: button component v4 (#938)
- feat(table): update for v4 (#930)
- v4 chore: add ts paths (#952)
- feat: migrate f36-inputs/checkbox to v4 [HOMER-24] (#944)
- feat: follow guidelines for f36-inputs [HOMER-37] (#950)
- feat: move HelpText to a separate package (#953)
- fix: add CloudUpload icon (#960)
- feat: extract Note to separate package (#969)
- Extract EmptyState to a separate package (#972)
- feat(label): extract to new @contentful/f36-forms package (#973)
- chore: bump parcel to beta-3 (#976)
- fix: ci memory issue
- fix: export BoxInternalProps
- v4 chore(deps): switch function specific lodash packages to lodash-es (#975)
- v4: add Timepicker to Storybook (#974)
- v4 chore(deps): move type deps to dependencies (#867)
- Update Label.tsx
- feat: enable passing props down to label in ControlledInput [Homer 25] (#977)
- feat: migrate f36-forms/controlled-input-field to v4 [HOMER-25] (#954)
- [wait for #954] feat: migrate radio button field to v4 [HOMER-38] (#961)
- fix: change CloudUpload icon
- fix: typescript issues after merge
- fix: introduce transparent variant of the button component (#1048)
- feat: migrate illustration component to icons [BAU-3] (#1029)
- feat(pill): migrate to V4 (#1034)
- feat(flex): add gap property (#1051)
- feat: rename Paragraph to Text (#1059)
- refactor: fix dependencies and improve types (#1068)
- feat: primitive optimizations (#1069)
- refactor(plop): update plop components generator (#1071)
- feat(tooltip-v4): refactor tooltip component for forma-v4 (#1047)
- feat(icons): add table icon (#1083)
- docs: Fix icons README and card story (#1098)
- fix(button): rename disabled prop to align with style guide (#1094)
- docs: remove Text margin from Card stories (#1099)
- build: fix noise from babel in v4 branch (#1105)
- feat: extract DragHandle component (#1093)
- fix: add missing deps to packages (#1107)
- feat: create ButtonGroup component (#1109)
- feat:V4 new color tokens (#1110)
- feat(TextLink) v4 (#1125)
- feat(ToggleButton) V4 (#1127)
- docs: move/update code style guide (#1130)
- refactor: inline all component variants [BAU-59] (#1131)
- chore: fix merge hiccup
- feat: skeleton v4 (#1139)
- feat: Accordion v4 (#1123)
- chore: small cleanup for consistency (#1144)
- feat(Puzzle): update Puzzle icon (#1145)
- refactor: css-in-js enforcement (#1149)
- chore: disable automatic releases
- refactor: V4 button (#1138)
- refactoring: more consistency and alignment about spacing props (#1155)
- feat: icon improvements (#1156)
- feat: bring back paragraph component (#1159)
- chore: enforce event handlers naming (#1161)
- chore: fix typo
- feat(tabs): migrate tabs to emotion (#1153)
- feat: Typography changes (#1163)
- test: remove snapshots tests from v4 (#1173)
- chore: enable auto deploy of the v4 packages (#1178)
- fix: remove prepublish from the codemod package (#1180)
- feat(copybutton): migrate copybutton to v4 (#1175)
- feat: filter out all polymorphic props (#1187)
- feat: text link codemod  (#1188)
- refactor: add icon postfix
- chore: small adjustments
- chore: fix test
- fix: typo
- chore: fixes
- chore: remove private labels for publishable packages (#1193)
- chore: fixes
- feat: improve TextLink codemod (#1192)
- chore: improve docs
- chore: small fixes
- feat: Modal v4 (#1179)
- chore: update yarn.lock
- chore: remove private from modal
- fix: add missing text-link dependency
- fix: add missing dependency
- fix: add missing testId
- docs: provide README for NPM purposes (#1194)
- fix: remove muted Badge variant (#1199)
- fix: small text link adjustments (#1197)
- feat: allow to migrate Tag to Badge by using codmod (#1196)
- feat(codemod): Migrate Badge with entityStatus (#1206)
- chore: update plop templates (#1207)
- feat(codemod): pill codemod (#1208)
- feat: Asset component migration (#1202)
- feat(V4): Notification component migration (#1201)
- chore: small improvements to storybook and plop template (#1209)
- feat: migrate datetime to v4 (#1200)
- feat: @contentful/f36-popover (#1204)
- fix: navigation component after merge with master
- test: update snapshots
- fix: autocomplete icon position
- test: remove flaky time mocks
- chore(codemod-v4-list): add codemod for transforming List component from v3 to v4 (#1227)
- fix: remove private from notification package
- fix: add popover to deps
- feat: removes EditorToolbar (#1231)
- feat: migrate datetime utility functions to v4 package (#1234)
- docs(list): fix list component docs (#1233)
- feat(codemod) Note component codemod (#1237)
- feat: Flex codemod (#1236)
- fix(list): add missing testId (#1238)
- docs(codemod): update @contentful/f36-codemod documentation (#1240)
- feat: v4 BaseInput (#1229)
- chore: remove timepicker component for v4 (#1242)
- refactor: remove IconButton (#1241)
- feat: Spinner codemod (#1243)
- fix(button): styles fix, component fix (#1246)
- fix(note): Note component styling fix (#1247)
- fix: Spinner codemod (#1248)
- feat: remove datepicker (#1253)
- docs: v4 website UI improvements (#1249)
- fix(pill): small visual improvements (#1244)
- feat: Table compound (#1250)
- chore: update lock file
- refactor(checkbox): Create BaseCheckbox component (#1235)
- refactor: compound components (#1254)
- feat: remove input package (#1260)
- refactor: adjustments to core utility types (#1228)
- fix: allow isDisabled property for CopyButton (#1262)
- feat: v4 TextInput component (#1230)
- feat(forms): Create Checkbox component (#1252)
- chore(Popover): make Popover compound (#1267)
- feat: FormControl (#1261)
-  feat: migrate textarea to v4 (#1265)
- ref [...]

2022-01-07 14:13 UTC, fabe commented
Maybe we could have use-case-based naming? e.g. `precise` or `exact`?

2022-01-07 14:17 UTC, andipaetzold commented
> Maybe we could have use-case-based naming? e.g. `precise` or `exact`?

@fabe That might cause issues if we somewhere want to display milliseconds as well. But I agree that `precise` sounds better than `with-seconds`.

In general I love the [DateTimeFormat interface](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) where you enable parts with boolean flags. Having something like this in forma with the flags `date`, `time`, `seconds`, `weekday` would be a great interface and avoid naming issues. But I guess it's too late for discussing this now 😬

2022-01-10 09:54 UTC, bgutsol submitted a review, later dismissed
`forma-v4` branch was already merged to master. Please change the base to `master`

2022-01-10 11:43 UTC, bgutsol approved these changes
LGTM

2022-01-10 11:56 UTC, gui-santos requested changes
Looks good

I will only ask you to make the value camelCase, that's what we've been using for props
(e.g. spacingXl, colorBlue, endIcon, etc)

2022-01-10 11:56 UTC, gui-santos commented on packages/components/datetime/src/types.ts
> +  | 'full-with-seconds'
```suggestion
  | 'fullWithSeconds'
```

For values of props we prefer to use camelCase

2022-01-10 12:35 UTC, andipaetzold commented
@bgutsol @gui-santos Both happy with `fullWithSeconds` or should we go for `fullExact` as @fabe proposed?

2022-01-10 13:03 UTC, bgutsol commented
> fullWithSeconds

Don't have a strong preference, but `fullWithSeconds` sounds more clear to me

2022-01-10 13:04 UTC, bgutsol commented
> @bgutsol @gui-santos Both happy with `fullWithSeconds` or should we go for `fullExact` as @fabe proposed?

Don't have a strong preference, but fullWithSeconds sounds more clear to me

2022-01-10 13:09 UTC, gui-santos commented
> @bgutsol @gui-santos Both happy with `fullWithSeconds` or should we go for `fullExact` as @fabe proposed?
@andipaetzold 
I have no preference tbh 🤷 
both sound good to me

2022-01-10 13:12 UTC, fabe commented
I'd go for `fullWithSeconds` for now!

2022-01-11 11:54 UTC, bgutsol reviewed
@andipaetzold please, update from the latest master to get ci: check links fixed

2022-01-11 12:48 UTC, suevalov approved these changes

2022-01-11 13:04 UTC, andipaetzold commented
I'd need an approval in chromatic in order to merge this PR

2022-01-11 14:22 UTC, gui-santos approved these changes

2022-01-11 14:23 UTC, gui-santos commented
> I'd need an approval in chromatic in order to merge this PR

@andipaetzold done
Thanks a lot for this contribution 🙌

2022-01-11 14:37 UTC, merged

2022-01-11 17:01 UTC, andipaetzold commented
Any idea why the released types are not up to date?

https://unpkg.com/@contentful/f36-datetime@4.1.0/dist/types.d.ts

`DateFormat` is missing the new `fullWithSeconds` option

2022-01-11 17:03 UTC, suevalov commented
@andipaetzold is it only types or the code is also missing?

2022-01-12 09:27 UTC, andipaetzold commented
@suevalov The code itself is there.

(Search for `fullWithSeconds` in https://unpkg.com/browse/@contentful/f36-datetime@4.1.0/dist/main.js)

2022-01-12 12:35 UTC, bgutsol commented
> @suevalov The code itself is there.
> 
> (Search for `fullWithSeconds` in https://unpkg.com/browse/@contentful/f36-datetime@4.1.0/dist/main.js)

@andipaetzold  we redeployed it, and now it has proper types in v `4.1.1`:  https://unpkg.com/@contentful/f36-datetime@4.1.1/dist/types.d.ts