docs(asset): asset documentation improvements
contentful/forma-36 pull request #1786
Opened 2022-01-17 15:25 UTC by massao

2022-01-17 16:32 UTC, gui-santos requested changes

2022-01-17 16:32 UTC, gui-santos commented on packages/components/asset/README.mdx
>  typescript: ./Asset.tsx
There is something wrong with the PropsTable, could you check it please?

![Screenshot 2022-01-17 at 17 31 59](https://user-images.githubusercontent.com/6597467/149807306-f817855b-fa18-4090-8c2d-5f960419513d.png)

2022-01-18 13:45 UTC, thebesson approved these changes

2022-01-19 07:38 UTC, Lelith approved these changes
Looks good to me!
![](https://media.giphy.com/media/brDwVn5kGIz3W/giphy.gif)

2022-01-19 13:41 UTC, gui-santos approved these changes

2022-01-19 13:56 UTC, merged