fix: allow children to be passed to InlineEntryCard
contentful/forma-36 pull request #1884
Opened 2022-02-11 14:38 UTC by gui-santos

# Purpose of PR

![Screenshot 2022-02-11 at 12 56 39](https://user-images.githubusercontent.com/6597467/153611016-ea9048b3-0ed6-4b84-9904-ddcd5a91da76.png)

We've made a mistake in the past. I think we assumed the `InlineEntryCard` only needed `title`, but because of that we created a bug in Rich Text editor where the title is being rendered as the content of the card:

![image](https://user-images.githubusercontent.com/6597467/153611243-099dd564-7acd-409d-8c95-e42494ad9263.png)

The title was supposed to be a prop to just render the native HTML tooltip (see first image)

## PR Checklist

- [ ] I have read the relevant `readme.md` file(s)
- [ ] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [ ] Tests are added/updated/not required
- [ ] Tests are passing
- [ ] Storybook stories are added/updated/not required
- [ ] Usage notes are added/updated/not required
- [ ] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [ ] Doesn't contain any sensitive information

2022-02-11 14:47 UTC, z0al approved these changes
🥇

2022-02-14 09:37 UTC, z0al commented
> wouldn't we want to use a `Tooltip` instead?

I think the point here is to maintain the existing functionality: having `props.children` for body and `title` for the on-hover text.

I don't have an opinion here and I also don't think my team would mind it if F36 used the Tooltip component internally instead of the native HTML title. Maybe double-check with Design?

2022-02-14 14:12 UTC, gui-santos commented
@denkristoffer 

After talking to @damann 
I updated the code to use our Tooltip! 🙌

2022-02-14 14:37 UTC, denkristoffer requested changes

2022-02-14 14:37 UTC, denkristoffer commented on packages/components/card/src/InlineEntryCard/InlineEntryCard.tsx
> +  console.log({ title, children });
Left over 🙂

2022-02-14 14:56 UTC, gui-santos commented on packages/components/card/src/InlineEntryCard/InlineEntryCard.tsx
> +  console.log({ title, children });
oops! hahahah

2022-02-14 15:13 UTC, massao approved these changes

2022-02-14 15:13 UTC, massao commented on packages/components/card/src/EntryCard/EntryCard.types.ts
> +   * The title of the entry, it will be used as the value for the native HTML attribute "title"
```suggestion
   * The title of the entry, it will be used as the value for the tooltip
```

2022-02-14 16:16 UTC, denkristoffer approved these changes

2022-02-14 16:16 UTC, merged