feat: add textarea handleing on textfield codemod
contentful/forma-36 pull request #2208
Opened 2022-09-09 12:22 UTC by massao

# Purpose of PR

Add handling of textfields that had a `textarea` prop on the codemod.

2022-09-09 12:36 UTC, denkristoffer requested changes

2022-09-09 12:36 UTC, denkristoffer commented on packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-text-field.output.js
> +import { FormControl, TextInput, Flex, TextArea } from "@contentful/f36-components";
```suggestion
import { FormControl, TextInput, Flex, Textarea } from "@contentful/f36-components";
```

2022-09-09 12:36 UTC, denkristoffer commented on packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-text-field.output.js
> +  <TextArea name="textarea" value="some value" rows={5} />
```suggestion
  <Textarea name="textarea" value="some value" rows={5} />
```

2022-09-09 12:36 UTC, denkristoffer commented on packages/forma-36-codemod/transforms/v4-text-field.js
> +        componentsToImport.push('TextArea');
```suggestion
        componentsToImport.push('Textarea');
```

2022-09-09 12:36 UTC, denkristoffer commented on packages/forma-36-codemod/transforms/v4-text-field.js
> +      if (isTextarea && !componentsToImport.includes('TextArea')) {
```suggestion
      if (isTextarea && !componentsToImport.includes('Textarea')) {
```

2022-09-09 12:36 UTC, denkristoffer commented on packages/forma-36-codemod/transforms/v4-text-field.js
> +        componentName: isTextarea ? 'TextArea' : 'TextInput',
```suggestion
        componentName: isTextarea ? 'Textarea' : 'TextInput',
```

2022-09-09 12:38 UTC, denkristoffer commented
This makes me think we might want to test that the code from our codemods can be compiled, so we don't just match input to output, but also try to build it.

2022-09-09 15:16 UTC, denkristoffer approved these changes

2022-09-12 06:30 UTC, Lelith approved these changes
Looks good to me!
![](https://media.giphy.com/media/H75SVhmkdFHOM/giphy.gif)

2022-09-12 10:51 UTC, merged