feat: New Component Avatar Group [HOMER-2118]
contentful/forma-36 pull request #2518
Opened 2023-07-04 12:57 UTC by Lelith

# Purpose of PR

Introduces a new component for grouping Avatars. It comes in two sizes and two different designs (stacked and spaced). It will show a maximum of 3 Avatar children, the rest of the children get rendered as a Menu. 
The Avatar components require an alt-text which will be displayed as the user name.

<img width="216" alt="image" src="https://github.com/contentful/forma-36/assets/1789174/dfe600b1-cb8c-4a3d-9d23-756fea2515bb">

<img width="230" alt="image" src="https://github.com/contentful/forma-36/assets/1789174/e479219a-94df-4507-ab5f-48723860ef3f">

2023-07-06 11:20 UTC, mdmjg approved these changes

2023-07-06 12:22 UTC, miguelcrespo approved these changes
I also don't see the new component in the preview: https://forma-36-git-feat-avatargrouphomer-2118.colorfuldemo.com/components/avatar

Is this expected?

2023-07-06 12:22 UTC, miguelcrespo commented on packages/components/avatar/README.mdx
> +```
question: based on the example of the `Avatar` shouldn't this headings be under `## Examples` ?

It also doesn't have the `import` section

2023-07-06 12:30 UTC, denkristoffer requested changes
The docs are broken: https://forma-36-git-feat-avatargrouphomer-2118.colorfuldemo.com/components/avatar

At least one of the errors is because the new component has not been added to the SandpackRenderer and LiveEditor.

2023-07-07 11:58 UTC, denkristoffer commented on packages/components/avatar/src/AvatarGroup/AvatarGroup.tsx
> +  spacing?: SpacingTokens;
I don't see the `spacing` prop being used anywhere, should it be?

2023-07-07 11:58 UTC, denkristoffer commented on packages/components/avatar/src/AvatarGroup/AvatarGroup.tsx
> +      data-test-id={testId}
```suggestion
      testId={testId}
```

2023-07-07 13:00 UTC, denkristoffer commented
Can you please bump the package.json version? You can do it with `npm run-script prerelease` or manually.

2023-07-07 13:48 UTC, miguelcrespo commented
> Can you please bump the package.json version? You can do it with `npm run-script prerelease` or manually.

@denkristoffer Done

2023-07-07 14:05 UTC, denkristoffer approved these changes

2023-07-07 16:57 UTC, merged