feat: Introduce new properties for the Avatar component [HOMER-2119]
contentful/forma-36 pull request #2519
Opened 2023-07-04 13:45 UTC by miguelcrespo

# Purpose of PR

This PR adds the following new properties to the `Avatar` component:
- showColorBorders
- isPrimary
- isActive
- icon

And replace enums for sizes and variants with simple string types

<img width="1180" alt="image" src="https://github.com/contentful/forma-36/assets/5839623/83f52084-00f8-4f8b-b1e9-8f5c0f721c3d">

## PR Checklist

- [X] I have read the relevant `readme.md` file(s)
- [X] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/main/packages/forma-36-react-components#commits)
- [X] Tests are added/updated/not required
- [X] Tests are passing
- [X] Storybook stories are added/updated/not required
- [X] Usage notes are added/updated/not required
- [X] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [X] Doesn't contain any sensitive information

2023-07-04 13:54 UTC, Lelith approved these changes
Looks good to me!
![](https://media.giphy.com/media/H75SVhmkdFHOM/giphy.gif)

2023-07-04 14:26 UTC, denkristoffer requested changes
Overall this looks good.

- The loading skeleton seems to have broken: https://forma-36-git-feat-homer-2119.colorfuldemo.com/components/avatar#loading-skeleton
- I don't see any differences between active an inactive: https://forma-36-git-feat-homer-2119.colorfuldemo.com/components/avatar#isactive

2023-07-04 14:26 UTC, denkristoffer commented on packages/components/avatar/README.mdx
> +- **user** - default variant
Let's keep the lists as they were for the docs website, it looks better and I don't think we need the literal values here, they are listed in both examples and the prop table.

2023-07-04 14:26 UTC, denkristoffer commented on packages/components/avatar/src/Avatar.tsx
> +  showColorBorders?: boolean;
```suggestion
  showColorBorder?: boolean;
```

I think singular `showColorBorder` fits better here, it's also what you've used yourself in a few places ;D

2023-07-05 10:09 UTC, miguelcrespo commented
@denkristoffer Hi Kristoffer, thanks for the review, I just addressed all the comments

2023-07-05 12:01 UTC, denkristoffer approved these changes
Thanks, looks good to me!

2023-07-05 13:22 UTC, merged