fix: update color warning [TOL-1801]
contentful/forma-36 pull request #2681
Opened 2024-02-23 14:14 UTC by 2wce

# Purpose of PR

In the `EntityStatusBadge` component when we have a scheduled action the icon fill color (orange-400 is the value for the warning variant for icons) is different from the status text color (orange 600 is the default). This was not intentional so this PR aims to fix that

## PR Checklist

- [ ] I have read the relevant `readme.md` file(s)
- [ ] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/main/packages/forma-36-react-components#commits)
- [ ] Tests are added/updated/not required
- [ ] Tests are passing
- [ ] Storybook stories are added/updated/not required
- [ ] Usage notes are added/updated/not required
- [ ] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [ ] Doesn't contain any sensitive information

2024-02-23 15:39 UTC, cf-remylenoir commented
_The failing CI is not related to your changes, waiting on the PR fix to be green._

2024-02-23 15:50 UTC, cf-remylenoir commented on package-lock.json
This can be removed 👀

2024-02-23 17:09 UTC, 2wce commented
Cool I'll update the PR on Monday so @cf-remylenoir we can merge then

2024-02-26 15:59 UTC, Lelith approved these changes
@2wce don 't forget to run npx changeset to get the version bump automated after merge

![](https://media.giphy.com/media/q5J2HfnH8mCvS/giphy.gif)

2024-02-26 16:18 UTC, cf-remylenoir requested changes
Happy to approve when the lock is removed + changeset added 🙂

2024-04-02 08:22 UTC, cf-remylenoir approved these changes
Apologies for the late review, I had my head down with the Studio GA 😄 Thank you for your contribution!

2024-04-03 08:54 UTC, merged

2024-04-03 09:12 UTC, cf-remylenoir commented
@all-contributors please add @2wce for code