fix: use FieldGroup classname property
contentful/forma-36 pull request #542
Opened 2020-08-20 15:49 UTC by djagya

# Purpose of PR

Fixes `FieldGroup` which wasn't using a passed `className`.

2020-08-20 19:23 UTC, burakukula approved these changes

2020-08-20 20:58 UTC, m10l requested changes
Nice spot! Travis is currently failing because there are some snapshot tests that need to be updated. Good to go after that :)

2020-08-20 23:25 UTC, djagya commented
Thanks for pointing me! Fixed

2020-08-24 10:32 UTC, m10l approved these changes
🚀

2020-08-24 10:58 UTC, merged