fix(accordionitem): add handleOpen and handleClose to log when items …
contentful/forma-36 pull request #593
Opened 2020-10-14 15:56 UTC by gregferg

# Purpose of PR

Adds handleOpen and handleClose to `AccordionItem.tsx` so that we can log when the accordionItems are opened and closed.

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [x] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

2020-10-14 16:06 UTC, gui-santos requested changes
Looks good! Just a suggestion regarding naming the props :)

2020-10-15 05:32 UTC, m10l approved these changes

2020-10-15 06:19 UTC, m10l commented
Just a heads up, Travis is failing because of these errors:

```
  61:9   error    'accordionId' is assigned a value but never used                              @typescript-eslint/no-unused-vars
  62:9   error    'expandedClass' is assigned a value but never used                            @typescript-eslint/no-unused-vars
```

2020-10-15 08:27 UTC, gui-santos commented on packages/forma-36-react-components/src/components/Accordion/AccordionItem/AccordionItem.tsx
> +  handleClose?: Function;
I'm telling you English is weird

https://www.youtube.com/watch?v=QO178ZfEVME

2020-10-15 11:35 UTC, gregferg commented on packages/forma-36-react-components/src/components/Accordion/AccordionItem/AccordionItem.tsx
> +  handleClose?: Function;
That it is haha

2020-10-15 11:48 UTC, gui-santos approved these changes
🙌

2020-10-15 12:08 UTC, merged