feat v4: rename packages
contentful/forma-36 pull request #853
Opened 2021-03-01 09:01 UTC by denkristoffer

# Purpose of PR

Rename packages as planned in #811

2021-03-01 13:44 UTC, suevalov requested changes
Can we keep folder names untouched and only rename package names for the time being? 

It would be easier for merging changes from v3 and will create less noise in V4 pull request.

2021-03-01 14:43 UTC, denkristoffer commented
@suevalov Fair point, thanks. Fixed.

2021-03-01 15:55 UTC, suevalov reviewed
I'd be also in favor of bumping all packages manually to version 4.0.0 in package.json

2021-03-01 16:46 UTC, denkristoffer commented
Yeah I was wondering about that, does semantic release just continue on from the set version?

2021-03-02 08:53 UTC, suevalov commented
@denkristoffer yes, the semantic release should pick it up from package.json

2021-03-02 08:54 UTC, suevalov approved these changes
👍🏼 from me, but let's collect a couple of more reviews before merging this one

2021-03-02 09:23 UTC, gui-santos approved these changes
![giphy](https://user-images.githubusercontent.com/6597467/109626894-54291000-7b41-11eb-9a1f-934b46ec394d.gif)

2021-03-03 14:23 UTC, mshaaban0 approved these changes

2021-03-03 14:23 UTC, mshaaban0 commented on packages/forma-36-fcss/package.json
> +  "version": "4.0.0",
🔥

2021-03-05 08:29 UTC, merged