feat: extract List to a separate package
contentful/forma-36 pull request #918
Opened 2021-04-13 07:35 UTC by nikazawila

This moves `List` to a separate component for v4

2021-04-13 08:56 UTC, denkristoffer requested changes
Thanks for tackling this 🙏 I think we should take advantage of our polymorphic building block components here, probably the `Box` in this case.

2021-04-13 08:56 UTC, denkristoffer commented on packages/components/list/src/List.tsx
> +}
I think we should use our polymorphic components here, maybe just a `Box` that can be either `ul` or `ol`? That would also give us the shared props like `testId` and `className` 🙂

2021-04-13 13:03 UTC, nikazawila commented
I'd appreciate some help on figuring out what I did wrong that the deployment fails...

2021-04-13 13:36 UTC, denkristoffer commented on packages/components/list/src/ListItem/ListItem.tsx
> +}
I think we should also use `CommonProps` for this component.

2021-04-13 14:13 UTC, denkristoffer commented on packages/components/list/src/List.tsx
> +> = ({ as: Tag = 'ul', className, children, ...otherProps }, ref) => {
```suggestion
> = ({ as: Tag = DEFAULT_TAG, className, children, ...otherProps }, ref) => {
```

2021-04-13 14:14 UTC, denkristoffer commented on packages/components/list/src/List.tsx
> +> = ({ as: Tag = 'ul', className, children, ...otherProps }, ref) => {
One last thing 🙂

2021-04-14 09:38 UTC, denkristoffer approved these changes

2021-04-14 09:38 UTC, merged